CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS mart;

GRANT USAGE ON SCHEMA staging, core, mart TO dvf_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA staging TO dvf_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO dvf_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA mart TO dvf_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT ALL ON TABLES TO dvf_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON TABLES TO dvf_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA mart GRANT ALL ON TABLES TO dvf_user;
